version: '3'

services: 
  nodejs:
    build: 
      context: .
  nginx:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/diegomatias.dev/cert.pem:/etc/nginx/cert.pem
      - /etc/letsencrypt/live/diegomatias.dev/privkey.pem:/etc/nginx/privkey.pem