version: '3'

services: 
  nodejs:
    build: 
      context: .
  nginx:
    image: nginx:mainline-alpine
    ports:
      - "8080:80"
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/diegomatias.dev/:/etc/letsencrypt/live/diegomatias.dev/